//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface PaginatedResponseOfAirportDto {
    data?: AirportDto[];
    pagination?: PaginationMetadata;
}

export interface AirportDto {
    siteNo?: string;
    icaoId?: string | undefined;
    arptId?: string | undefined;
    arptName?: string | undefined;
    siteTypeCode?: string | undefined;
    city?: string | undefined;
    stateCode?: string | undefined;
    countryCode?: string | undefined;
    stateName?: string | undefined;
    latDecimal?: number | undefined;
    longDecimal?: number | undefined;
    elev?: number | undefined;
    magVarn?: number | undefined;
    magHemis?: string | undefined;
    chartName?: string | undefined;
    arptStatus?: string | undefined;
    fuelTypes?: string | undefined;
    lastInspection?: Date | undefined;
    lastInfoResponse?: Date | undefined;
    customsFlag?: string | undefined;
    lndgRightsFlag?: string | undefined;
    jointUseFlag?: string | undefined;
    milLndgFlag?: string | undefined;
    contactTitle?: string | undefined;
    contactName?: string | undefined;
    contactAddress1?: string | undefined;
    contactAddress2?: string | undefined;
    contactCity?: string | undefined;
    contactState?: string | undefined;
    contactZipCode?: string | undefined;
    contactZipPlusFour?: string | undefined;
    contactPhoneNumber?: string | undefined;
}

export interface PaginationMetadata {
    nextCursor?: string | undefined;
    hasMore?: boolean;
    limit?: number;
}

export interface ApiErrorResponse {
    code?: string;
    message?: string;
    details?: string | undefined;
    validationErrors?: { [key: string]: string[]; } | undefined;
    timestamp?: string;
    traceId?: string | undefined;
    path?: string | undefined;
}

export interface RunwayDto {
    id?: string;
    runwayId?: string;
    length?: number | undefined;
    width?: number | undefined;
    surfaceType?: RunwaySurfaceType;
    surfaceTreatment?: RunwaySurfaceTreatment;
    pavementClassification?: string | undefined;
    edgeLightIntensity?: RunwayEdgeLightIntensity;
    weightBearingSingleWheel?: number | undefined;
    weightBearingDualWheel?: number | undefined;
    weightBearingDualTandem?: number | undefined;
    weightBearingDoubleDualTandem?: number | undefined;
    runwayEnds?: RunwayEndDto[];
}

export enum RunwaySurfaceType {
    Unknown = "Unknown",
    Concrete = "Concrete",
    Asphalt = "Asphalt",
    Snow = "Snow",
    Ice = "Ice",
    Mats = "Mats",
    Treated = "Treated",
    Gravel = "Gravel",
    Turf = "Turf",
    Dirt = "Dirt",
    PartiallyPaved = "PartiallyPaved",
    Rooftop = "Rooftop",
    Water = "Water",
    Aluminum = "Aluminum",
    Brick = "Brick",
    Caliche = "Caliche",
    Coral = "Coral",
    Deck = "Deck",
    Grass = "Grass",
    Metal = "Metal",
    NonStandard = "NonStandard",
    OilChip = "OilChip",
    Psp = "Psp",
    Sand = "Sand",
    Sod = "Sod",
    Steel = "Steel",
    Wood = "Wood",
}

export enum RunwaySurfaceTreatment {
    Unknown = "Unknown",
    None = "None",
    Grooved = "Grooved",
    PorousFrictionCourse = "PorousFrictionCourse",
    AggregateFrictionSealCoat = "AggregateFrictionSealCoat",
    RubberizedFrictionSealCoat = "RubberizedFrictionSealCoat",
    WireComb = "WireComb",
}

export enum RunwayEdgeLightIntensity {
    Unknown = "Unknown",
    None = "None",
    High = "High",
    Medium = "Medium",
    Low = "Low",
    Flood = "Flood",
    NonStandard = "NonStandard",
    Perimeter = "Perimeter",
    Strobe = "Strobe",
}

export interface RunwayEndDto {
    id?: string;
    runwayEndId?: string;
    trueAlignment?: number | undefined;
    approachType?: InstrumentApproachType;
    rightHandTrafficPattern?: boolean;
    markingsType?: RunwayMarkingsType;
    markingsCondition?: RunwayMarkingsCondition;
    latitude?: number | undefined;
    longitude?: number | undefined;
    elevation?: number | undefined;
    thresholdCrossingHeight?: number | undefined;
    visualGlidePathAngle?: number | undefined;
    displacedThresholdLatitude?: number | undefined;
    displacedThresholdLongitude?: number | undefined;
    displacedThresholdElevation?: number | undefined;
    displacedThresholdLength?: number | undefined;
    touchdownZoneElevation?: number | undefined;
    visualGlideSlopeIndicator?: VisualGlideSlopeIndicatorType;
    runwayVisualRangeEquipment?: string | undefined;
    runwayVisibilityValueEquipment?: boolean;
    approachLightSystem?: ApproachLightSystemType;
    hasRunwayEndLights?: boolean;
    hasCenterlineLights?: boolean;
    hasTouchdownZoneLights?: boolean;
    controllingObjectDescription?: string | undefined;
    controllingObjectMarking?: ControllingObjectMarking;
    controllingObjectClearanceSlope?: number | undefined;
    controllingObjectHeightAboveRunway?: number | undefined;
    controllingObjectDistanceFromRunway?: number | undefined;
    controllingObjectCenterlineOffset?: string | undefined;
}

export enum InstrumentApproachType {
    Unknown = "Unknown",
    None = "None",
    Ils = "Ils",
    Mls = "Mls",
    Sdf = "Sdf",
    Localizer = "Localizer",
    Lda = "Lda",
    Ismls = "Ismls",
    IlsDme = "IlsDme",
    SdfDme = "SdfDme",
    LocDme = "LocDme",
    LocGs = "LocGs",
    LdaDme = "LdaDme",
}

export enum RunwayMarkingsType {
    Unknown = "Unknown",
    None = "None",
    PrecisionInstrument = "PrecisionInstrument",
    NonPrecisionInstrument = "NonPrecisionInstrument",
    Basic = "Basic",
    NumbersOnly = "NumbersOnly",
    NonStandard = "NonStandard",
    Buoys = "Buoys",
    Stol = "Stol",
}

export enum RunwayMarkingsCondition {
    Unknown = "Unknown",
    Good = "Good",
    Fair = "Fair",
    Poor = "Poor",
}

export enum VisualGlideSlopeIndicatorType {
    Unknown = "Unknown",
    None = "None",
    Savasi2BoxLeft = "Savasi2BoxLeft",
    Savasi2BoxRight = "Savasi2BoxRight",
    Vasi2BoxLeft = "Vasi2BoxLeft",
    Vasi2BoxRight = "Vasi2BoxRight",
    Vasi4BoxLeft = "Vasi4BoxLeft",
    Vasi4BoxRight = "Vasi4BoxRight",
    Vasi6BoxLeft = "Vasi6BoxLeft",
    Vasi6BoxRight = "Vasi6BoxRight",
    Vasi12Box = "Vasi12Box",
    Vasi16Box = "Vasi16Box",
    Papi2LightLeft = "Papi2LightLeft",
    Papi2LightRight = "Papi2LightRight",
    Papi4LightLeft = "Papi4LightLeft",
    Papi4LightRight = "Papi4LightRight",
    TriColorLeft = "TriColorLeft",
    TriColorRight = "TriColorRight",
    PulsatingLeft = "PulsatingLeft",
    PulsatingRight = "PulsatingRight",
    PanelLeft = "PanelLeft",
    PanelRight = "PanelRight",
    NonStandard = "NonStandard",
    PrivateUse = "PrivateUse",
    NonSpecificVasi = "NonSpecificVasi",
}

export enum ApproachLightSystemType {
    Unknown = "Unknown",
    None = "None",
    AirForceOverrun = "AirForceOverrun",
    Alsaf = "Alsaf",
    Alsf1 = "Alsf1",
    Alsf2 = "Alsf2",
    Mals = "Mals",
    Malsf = "Malsf",
    Malsr = "Malsr",
    Rail = "Rail",
    Sals = "Sals",
    Salsf = "Salsf",
    Ssals = "Ssals",
    Ssalf = "Ssalf",
    Ssalr = "Ssalr",
    Odals = "Odals",
    Rlls = "Rlls",
    MilitaryOverrun = "MilitaryOverrun",
    NonStandard = "NonStandard",
}

export enum ControllingObjectMarking {
    Unknown = "Unknown",
    None = "None",
    Marked = "Marked",
    Lighted = "Lighted",
    MarkedAndLighted = "MarkedAndLighted",
}

export interface AirportDiagramsResponseDto {
    airportName?: string;
    icaoIdent?: string | undefined;
    airportIdent?: string | undefined;
    diagrams?: AirportDiagramDto[];
}

export interface AirportDiagramDto {
    chartName?: string;
    pdfUrl?: string;
}

export interface AirsigmetDto {
    id?: number;
    rawText?: string | undefined;
    validTimeFrom?: string | undefined;
    validTimeTo?: string | undefined;
    altitude?: AirsigmetAltitude | undefined;
    movementDirDegrees?: number | undefined;
    movementSpeedKt?: number | undefined;
    hazard?: AirsigmetHazardDto | undefined;
    airsigmetType?: string | undefined;
    areas?: AirsigmetArea[] | undefined;
}

export interface AirsigmetAltitude {
    minFtMsl?: number | undefined;
    maxFtMsl?: number | undefined;
}

export interface AirsigmetHazardDto {
    type?: AirsigmetHazardType | undefined;
    severity?: string | undefined;
}

export enum AirsigmetHazardType {
    CONVECTIVE = 0,
    ICE = 1,
    TURB = 2,
    IFR = 3,
    MTN_OBSCN = 4,
}

export interface AirsigmetArea {
    numPoints?: number;
    points?: AirsigmetPoint[];
}

export interface AirsigmetPoint {
    longitude?: number;
    latitude?: number;
}

export interface PaginatedResponseOfAirspaceDto {
    data?: AirspaceDto[];
    pagination?: PaginationMetadata;
}

export interface AirspaceDto {
    globalId?: string | undefined;
    ident?: string | undefined;
    icaoId?: string | undefined;
    name?: string | undefined;
    upperDesc?: string | undefined;
    upperVal?: number | undefined;
    upperUom?: string | undefined;
    upperCode?: string | undefined;
    lowerDesc?: string | undefined;
    lowerVal?: number | undefined;
    lowerUom?: string | undefined;
    lowerCode?: string | undefined;
    typeCode?: string | undefined;
    localType?: string | undefined;
    class?: string | undefined;
    milCode?: string | undefined;
    commName?: string | undefined;
    level?: string | undefined;
    sector?: string | undefined;
    onshore?: string | undefined;
    exclusion?: string | undefined;
    wkhrCode?: string | undefined;
    wkhrRmk?: string | undefined;
    dst?: string | undefined;
    gmtOffset?: string | undefined;
    contAgent?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    adhpId?: string | undefined;
    geometry?: GeoJsonGeometry | undefined;
}

export interface GeoJsonGeometry {
    type?: string;
    coordinates?: number[][][];
}

export interface PaginatedResponseOfSpecialUseAirspaceDto {
    data?: SpecialUseAirspaceDto[];
    pagination?: PaginationMetadata;
}

export interface SpecialUseAirspaceDto {
    globalId?: string | undefined;
    name?: string | undefined;
    typeCode?: string | undefined;
    class?: string | undefined;
    upperDesc?: string | undefined;
    upperVal?: string | undefined;
    upperUom?: string | undefined;
    upperCode?: string | undefined;
    lowerDesc?: string | undefined;
    lowerVal?: string | undefined;
    lowerUom?: string | undefined;
    lowerCode?: string | undefined;
    levelCode?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    contAgent?: string | undefined;
    commName?: string | undefined;
    sector?: string | undefined;
    onshore?: string | undefined;
    exclusion?: string | undefined;
    timesOfUse?: string | undefined;
    gmtOffset?: string | undefined;
    dstCode?: string | undefined;
    remarks?: string | undefined;
    geometry?: GeoJsonGeometry | undefined;
}

export interface ChartSupplementsResponseDto {
    airportName?: string | undefined;
    airportCity?: string | undefined;
    airportCode?: string | undefined;
    supplements?: ChartSupplementDto[];
}

export interface ChartSupplementDto {
    pdfUrl?: string;
}

export interface PaginatedResponseOfCommunicationFrequencyDto {
    data?: CommunicationFrequencyDto[];
    pagination?: PaginationMetadata;
}

export interface CommunicationFrequencyDto {
    id?: string;
    facilityCode?: string | undefined;
    effectiveDate?: Date;
    facilityName?: string | undefined;
    facilityType?: string;
    artccOrFssId?: string | undefined;
    cpdlc?: string | undefined;
    towerHours?: string | undefined;
    servicedFacility?: string;
    servicedFacilityName?: string | undefined;
    servicedSiteType?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    servicedCity?: string | undefined;
    servicedState?: string | undefined;
    servicedCountry?: string | undefined;
    towerOrCommCall?: string | undefined;
    primaryApproachRadioCall?: string | undefined;
    frequency?: string | undefined;
    sectorization?: string | undefined;
    frequencyUse?: string | undefined;
    remark?: string | undefined;
}

export interface GAirmetDto {
    id?: number;
    receiptTime?: Date;
    issueTime?: Date;
    expireTime?: Date;
    validTime?: Date;
    product?: GAirmetProduct;
    tag?: string | undefined;
    forecastHour?: number;
    hazard?: GAirmetHazardType | undefined;
    hazardSeverity?: string | undefined;
    geometryType?: string | undefined;
    dueTo?: string | undefined;
    altitudes?: GAirmetAltitude[] | undefined;
    area?: GAirmetArea | undefined;
}

export enum GAirmetProduct {
    SIERRA = 0,
    TANGO = 1,
    ZULU = 2,
}

export enum GAirmetHazardType {
    MT_OBSC = 0,
    IFR = 1,
    TURB_LO = 2,
    TURB_HI = 3,
    LLWS = 4,
    SFC_WIND = 5,
    ICE = 6,
    FZLVL = 7,
    M_FZLVL = 8,
}

export interface GAirmetAltitude {
    minFtMsl?: string | undefined;
    maxFtMsl?: string | undefined;
    levelFtMsl?: string | undefined;
    fzlAltitude?: GAirmetFzlAltitude | undefined;
}

export interface GAirmetFzlAltitude {
    minFtMsl?: string | undefined;
    maxFtMsl?: string | undefined;
}

export interface GAirmetArea {
    numPoints?: number;
    points?: GAirmetPoint[];
}

export interface GAirmetPoint {
    longitude?: number;
    latitude?: number;
}

export interface MetarDto {
    id?: number;
    rawText?: string | undefined;
    stationId?: string | undefined;
    observationTime?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    tempC?: number | undefined;
    dewpointC?: number | undefined;
    windDirDegrees?: string | undefined;
    windSpeedKt?: number | undefined;
    windGustKt?: number | undefined;
    visibilityStatuteMi?: string | undefined;
    altimInHg?: number | undefined;
    seaLevelPressureMb?: number | undefined;
    qualityControlFlags?: MetarQualityControlFlagsDto | undefined;
    wxString?: string | undefined;
    skyCondition?: MetarSkyConditionDto[] | undefined;
    flightCategory?: string | undefined;
}

export interface MetarQualityControlFlagsDto {
    corrected?: string | undefined;
    auto?: string | undefined;
    autoStation?: string | undefined;
    maintenanceIndicatorOn?: string | undefined;
    noSignal?: string | undefined;
    lightningSensorOff?: string | undefined;
    freezingRainSensorOff?: string | undefined;
    presentWeatherSensorOff?: string | undefined;
}

export interface MetarSkyConditionDto {
    skyCover?: string;
    cloudBaseFtAgl?: number | undefined;
}

export interface PaginatedResponseOfMetarDto {
    data?: MetarDto[];
    pagination?: PaginationMetadata;
}

export interface NavlogResponseDto {
    totalRouteDistance?: number;
    totalRouteTimeHours?: number;
    totalFuelUsed?: number;
    averageWindComponent?: number;
    legs?: NavigationLegDto[];
    airspaceGlobalIds?: string[];
    specialUseAirspaceGlobalIds?: string[];
    obstacleOasNumbers?: string[];
}

export interface NavigationLegDto {
    legStartPoint?: WaypointDto;
    legEndPoint?: WaypointDto;
    trueCourse?: number;
    magneticHeading?: number;
    magneticCourse?: number;
    groundSpeed?: number;
    legDistance?: number;
    distanceRemaining?: number;
    startLegTime?: Date;
    endLegTime?: Date;
    legFuelBurnGals?: number;
    remainingFuelGals?: number;
    windDir?: number;
    windSpeed?: number;
    headwindComponent?: number;
    tempC?: number;
}

export interface WaypointDto {
    id?: string;
    name?: string;
    latitude?: number;
    longitude?: number;
    altitude?: number;
    waypointType?: WaypointType | undefined;
    refuelGallons?: number | undefined;
    refuelToFull?: boolean | undefined;
    isRefuelingStop?: boolean | undefined;
}

export enum WaypointType {
    Airport = "Airport",
    Custom = "Custom",
    CalculatedPoint = "CalculatedPoint",
    Navaid = "Navaid",
}

export interface NavlogRequestDto {
    waypoints?: WaypointDto[];
    performanceData?: NavlogPerformanceDataDto;
    plannedCruisingAltitude?: number;
    timeOfDeparture?: Date;
}

export interface NavlogPerformanceDataDto {
    climbTrueAirspeed?: number;
    cruiseTrueAirspeed?: number;
    descentTrueAirspeed?: number;
    climbFpm?: number;
    descentFpm?: number;
    climbFuelBurn?: number;
    cruiseFuelBurn?: number;
    descentFuelBurn?: number;
    sttFuelGals?: number;
    fuelOnBoardGals?: number;
}

export interface BearingAndDistanceResponseDto {
    trueCourse?: number;
    magneticCourse?: number;
    distance?: number;
}

export interface BearingAndDistanceRequestDto {
    startLatitude?: number;
    startLongitude?: number;
    endLatitude?: number;
    endLongitude?: number;
}

export interface WindsAloftDto {
    validTime?: Date;
    forUseStartTime?: Date;
    forUseEndTime?: Date;
    windTemp?: WindsAloftSiteDto[];
}

export interface WindsAloftSiteDto {
    id?: string;
    lat?: number;
    lon?: number;
    windTemp?: { [key: string]: WindTempDto; };
}

export interface WindTempDto {
    direction?: number | undefined;
    speed?: number;
    temperature?: number | undefined;
}

export interface NotamResponseDto {
    notams?: NotamDto[];
    totalCount?: number;
    retrievedAt?: Date;
    queryLocation?: string | undefined;
}

export interface NotamDto {
    type?: string;
    id?: string | undefined;
    geometry?: NotamGeometryDto | undefined;
    properties?: NotamPropertiesDto | undefined;
}

export interface NotamGeometryDto {
    type?: string;
    coordinates?: any | undefined;
    geometries?: NotamGeometryDto[] | undefined;
}

export interface NotamPropertiesDto {
    coreNOTAMData?: CoreNotamDataDto | undefined;
}

export interface CoreNotamDataDto {
    notamEvent?: NotamEventDto | undefined;
    notam?: NotamDetailDto | undefined;
    notamTranslation?: NotamTranslationDto[] | undefined;
}

export interface NotamEventDto {
    encoding?: string | undefined;
    scenario?: string | undefined;
}

export interface NotamDetailDto {
    id?: string | undefined;
    number?: string | undefined;
    series?: string | undefined;
    year?: string | undefined;
    type?: string | undefined;
    issued?: string | undefined;
    affectedFir?: string | undefined;
    selectionCode?: string | undefined;
    traffic?: string | undefined;
    purpose?: string | undefined;
    scope?: string | undefined;
    minimumFl?: string | undefined;
    maximumFl?: string | undefined;
    location?: string | undefined;
    icaoLocation?: string | undefined;
    effectiveStart?: string | undefined;
    effectiveEnd?: string | undefined;
    estimated?: string | undefined;
    text?: string | undefined;
    classification?: string | undefined;
    cancelationDate?: string | undefined;
    accountId?: string | undefined;
    lastUpdated?: string | undefined;
    schedule?: string | undefined;
    lowerLimit?: string | undefined;
    upperLimit?: string | undefined;
    coordinates?: string | undefined;
    radius?: string | undefined;
}

export interface NotamTranslationDto {
    type?: string | undefined;
    simpleText?: string | undefined;
    domestic_message?: string | undefined;
    icao_message?: string | undefined;
    formattedText?: string | undefined;
}

export interface NotamQueryByRouteRequest {
    airportIdentifiers?: string[];
    routePoints?: RoutePointDto[];
    corridorRadiusNm?: number | undefined;
    includeCorridorNotams?: boolean;
}

export interface RoutePointDto {
    airportIdentifier?: string | undefined;
    name?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    radiusNm?: number | undefined;
    isAirport?: boolean;
}

export interface PaginatedResponseOfObstacleDto {
    data?: ObstacleDto[];
    pagination?: PaginationMetadata;
}

export interface ObstacleDto {
    oasNumber?: string;
    stateId?: string | undefined;
    cityName?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    obstacleType?: string | undefined;
    quantity?: number | undefined;
    heightAgl?: number | undefined;
    heightAmsl?: number | undefined;
    lighting?: ObstacleLighting;
    horizontalAccuracy?: HorizontalAccuracy;
    verticalAccuracy?: VerticalAccuracy;
    marking?: ObstacleMarking;
    verificationStatus?: VerificationStatus;
}

export enum ObstacleLighting {
    Unknown = "Unknown",
    Red = "Red",
    DualMediumWhiteStrobeRed = "DualMediumWhiteStrobeRed",
    HighIntensityWhiteStrobeRed = "HighIntensityWhiteStrobeRed",
    MediumIntensityWhiteStrobe = "MediumIntensityWhiteStrobe",
    HighIntensityWhiteStrobe = "HighIntensityWhiteStrobe",
    Flood = "Flood",
    DualMediumCatenary = "DualMediumCatenary",
    SynchronizedRedLighting = "SynchronizedRedLighting",
    Lighted = "Lighted",
    None = "None",
}

export enum HorizontalAccuracy {
    Unknown = "Unknown",
    Within20Feet = "Within20Feet",
    Within50Feet = "Within50Feet",
    Within100Feet = "Within100Feet",
    Within250Feet = "Within250Feet",
    Within500Feet = "Within500Feet",
    Within1000Feet = "Within1000Feet",
    WithinHalfNauticalMile = "WithinHalfNauticalMile",
    Within1NauticalMile = "Within1NauticalMile",
}

export enum VerticalAccuracy {
    Unknown = "Unknown",
    Within3Feet = "Within3Feet",
    Within10Feet = "Within10Feet",
    Within20Feet = "Within20Feet",
    Within50Feet = "Within50Feet",
    Within125Feet = "Within125Feet",
    Within250Feet = "Within250Feet",
    Within500Feet = "Within500Feet",
    Within1000Feet = "Within1000Feet",
}

export enum ObstacleMarking {
    Unknown = "Unknown",
    OrangeOrOrangeWhitePaint = "OrangeOrOrangeWhitePaint",
    WhitePaintOnly = "WhitePaintOnly",
    Marked = "Marked",
    FlagMarker = "FlagMarker",
    SphericalMarker = "SphericalMarker",
    None = "None",
}

export enum VerificationStatus {
    Unknown = "Unknown",
    Verified = "Verified",
    Unverified = "Unverified",
}

export interface AirportCrosswindResponseDto {
    airportIdentifier?: string;
    windDirectionDegrees?: number | undefined;
    windSpeedKt?: number;
    windGustKt?: number | undefined;
    isVariableWind?: boolean;
    rawMetar?: string | undefined;
    observationTime?: string | undefined;
    runways?: RunwayCrosswindComponentDto[];
    recommendedRunway?: string | undefined;
}

export interface RunwayCrosswindComponentDto {
    runwayEndId?: string;
    magneticHeadingDegrees?: number;
    crosswindKt?: number;
    headwindKt?: number;
    gustCrosswindKt?: number | undefined;
    gustHeadwindKt?: number | undefined;
    absoluteCrosswindKt?: number;
    hasHeadwind?: boolean;
}

export interface CrosswindCalculationResponseDto {
    crosswindKt?: number;
    headwindKt?: number;
    gustCrosswindKt?: number | undefined;
    gustHeadwindKt?: number | undefined;
    windDirectionDegrees?: number | undefined;
    windSpeedKt?: number;
    windGustKt?: number | undefined;
    runwayHeadingDegrees?: number;
    isVariableWind?: boolean;
}

export interface CrosswindCalculationRequestDto {
    windDirectionDegrees?: number | undefined;
    windSpeedKt?: number;
    windGustKt?: number | undefined;
    runwayHeadingDegrees?: number;
}

export interface DensityAltitudeResponseDto {
    airportIdentifier?: string | undefined;
    fieldElevationFt?: number;
    pressureAltitudeFt?: number;
    densityAltitudeFt?: number;
    isaTemperatureCelsius?: number;
    actualTemperatureCelsius?: number;
    temperatureDeviationCelsius?: number;
    altimeterInHg?: number;
    rawMetar?: string | undefined;
    observationTime?: string | undefined;
}

export interface DensityAltitudeRequestDto {
    fieldElevationFt?: number;
    altimeterInHg?: number;
    temperatureCelsius?: number;
}

export interface PirepDto {
    id?: number;
    rawText?: string | undefined;
    receiptTime?: string | undefined;
    observationTime?: string | undefined;
    qualityControlFlags?: PirepQualityControlFlags | undefined;
    aircraftRef?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    altitudeFtMsl?: number | undefined;
    skyConditions?: PirepSkyCondition[] | undefined;
    turbulenceConditions?: PirepTurbulenceCondition[] | undefined;
    icingConditions?: PirepIcingCondition[] | undefined;
    visibilityStatuteMi?: number | undefined;
    wxString?: string | undefined;
    tempC?: number | undefined;
    windDirDegrees?: number | undefined;
    windSpeedKt?: number | undefined;
    vertGustKt?: number | undefined;
    reportType?: string | undefined;
}

export interface PirepQualityControlFlags {
    midPointAssumed?: string | undefined;
    noTimeStamp?: string | undefined;
    fltLvlRange?: string | undefined;
    aboveGroundLevelIndicated?: string | undefined;
    noFltLvl?: string | undefined;
    badLocation?: string | undefined;
}

export interface PirepSkyCondition {
    skyCover?: string;
    cloudBaseFtMsl?: number | undefined;
    cloudTopFtMsl?: number | undefined;
}

export interface PirepTurbulenceCondition {
    turbulenceType?: string | undefined;
    turbulenceIntensity?: string | undefined;
    turbulenceBaseFtMsl?: number | undefined;
    turbulenceTopFtMsl?: number | undefined;
    turbulenceFreq?: string | undefined;
}

export interface PirepIcingCondition {
    icingType?: string | undefined;
    icingIntensity?: string | undefined;
    icingBaseFtMsl?: number | undefined;
    icingTopFtMsl?: number | undefined;
}

export interface TafDto {
    rawText?: string | undefined;
    stationId?: string | undefined;
    issueTime?: string | undefined;
    bulletinTime?: string | undefined;
    validTimeFrom?: string | undefined;
    validTimeTo?: string | undefined;
    remarks?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
    elevationM?: number | undefined;
    forecast?: TafForecast[] | undefined;
}

export interface TafForecast {
    fcstTimeFrom?: string | undefined;
    fcstTimeTo?: string | undefined;
    changeIndicator?: string | undefined;
    timeBecoming?: string | undefined;
    probability?: number | undefined;
    windDirDegrees?: string | undefined;
    windSpeedKt?: number | undefined;
    windGustKt?: number | undefined;
    windShearHgtFtAgl?: number | undefined;
    windShearDirDegrees?: number | undefined;
    windShearSpeedKt?: number | undefined;
    visibilityStatuteMi?: string | undefined;
    altimInHg?: number | undefined;
    vertVisFt?: number | undefined;
    wxString?: string | undefined;
    notDecoded?: string | undefined;
    skyConditions?: TafSkyCondition[] | undefined;
    turbulenceConditions?: TafTurbulenceCondition[] | undefined;
    icingConditions?: TafIcingCondition[] | undefined;
    temperature?: TafTemperature[] | undefined;
}

export interface TafSkyCondition {
    skyCover?: string;
    cloudBaseFtAgl?: number | undefined;
    cloudType?: string | undefined;
}

export interface TafTurbulenceCondition {
    turbulenceIntensity?: string | undefined;
    turbulenceMinAltFtAgl?: number | undefined;
    turbulenceMaxAltFtAgl?: number | undefined;
}

export interface TafIcingCondition {
    icingIntensity?: string | undefined;
    icingMinAltFtAgl?: number | undefined;
    icingMaxAltFtAgl?: number | undefined;
}

export interface TafTemperature {
    validTime?: string | undefined;
    sfcTempC?: number | undefined;
    maxTempC?: string | undefined;
    minTempC?: string | undefined;
}