/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DocsRateLimitsRouteImport } from './routes/docs/rate-limits'
import { Route as DocsOpenapiRouteImport } from './routes/docs/openapi'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsErrorsRouteImport } from './routes/docs/errors'
import { Route as DocsDataFreshnessRouteImport } from './routes/docs/data-freshness'
import { Route as DocsAuthenticationRouteImport } from './routes/docs/authentication'
import { Route as DocsApiReferenceRouteImport } from './routes/docs/api-reference'
import { Route as DashboardGettingStartedRouteImport } from './routes/dashboard/getting-started'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as DocsDataModelsIndexRouteImport } from './routes/docs/data-models/index'
import { Route as DocsCategoryIndexRouteImport } from './routes/docs/$category/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardKeysIndexRouteImport } from './routes/dashboard/keys/index'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard/billing/index'
import { Route as DocsDataModelsGroupRouteImport } from './routes/docs/data-models/$group'
import { Route as DocsCategoryOperationIdRouteImport } from './routes/docs/$category/$operationId'
import { Route as MarketingLegalTermsRouteImport } from './routes/_marketing/legal/terms'
import { Route as MarketingLegalPrivacyRouteImport } from './routes/_marketing/legal/privacy'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DocsRateLimitsRoute = DocsRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOpenapiRoute = DocsOpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDataFreshnessRoute = DocsDataFreshnessRouteImport.update({
  id: '/data-freshness',
  path: '/data-freshness',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGettingStartedRoute = DashboardGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const DocsDataModelsIndexRoute = DocsDataModelsIndexRouteImport.update({
  id: '/data-models/',
  path: '/data-models/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCategoryIndexRoute = DocsCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysIndexRoute = DashboardKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsDataModelsGroupRoute = DocsDataModelsGroupRouteImport.update({
  id: '/data-models/$group',
  path: '/data-models/$group',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCategoryOperationIdRoute = DocsCategoryOperationIdRouteImport.update({
  id: '/$category/$operationId',
  path: '/$category/$operationId',
  getParentRoute: () => DocsRoute,
} as any)
const MarketingLegalTermsRoute = MarketingLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalPrivacyRoute = MarketingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/pricing': typeof MarketingPricingRoute
  '/dashboard/getting-started': typeof DashboardGettingStartedRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/data-freshness': typeof DocsDataFreshnessRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/openapi': typeof DocsOpenapiRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
  '/docs/$category/$operationId': typeof DocsCategoryOperationIdRoute
  '/docs/data-models/$group': typeof DocsDataModelsGroupRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/keys/': typeof DashboardKeysIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/docs/$category/': typeof DocsCategoryIndexRoute
  '/docs/data-models/': typeof DocsDataModelsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/pricing': typeof MarketingPricingRoute
  '/dashboard/getting-started': typeof DashboardGettingStartedRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/data-freshness': typeof DocsDataFreshnessRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/openapi': typeof DocsOpenapiRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
  '/docs/$category/$operationId': typeof DocsCategoryOperationIdRoute
  '/docs/data-models/$group': typeof DocsDataModelsGroupRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/keys': typeof DashboardKeysIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/docs/$category': typeof DocsCategoryIndexRoute
  '/docs/data-models': typeof DocsDataModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/waitlist': typeof WaitlistRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/dashboard/getting-started': typeof DashboardGettingStartedRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/data-freshness': typeof DocsDataFreshnessRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/openapi': typeof DocsOpenapiRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_marketing/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/_marketing/legal/terms': typeof MarketingLegalTermsRoute
  '/docs/$category/$operationId': typeof DocsCategoryOperationIdRoute
  '/docs/data-models/$group': typeof DocsDataModelsGroupRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/keys/': typeof DashboardKeysIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/docs/$category/': typeof DocsCategoryIndexRoute
  '/docs/data-models/': typeof DocsDataModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/sign-in'
    | '/sign-up'
    | '/waitlist'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/dashboard/getting-started'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/data-freshness'
    | '/docs/errors'
    | '/docs/getting-started'
    | '/docs/openapi'
    | '/docs/rate-limits'
    | '/dashboard/'
    | '/docs/'
    | '/legal/privacy'
    | '/legal/terms'
    | '/docs/$category/$operationId'
    | '/docs/data-models/$group'
    | '/dashboard/billing/'
    | '/dashboard/keys/'
    | '/dashboard/settings/'
    | '/docs/$category/'
    | '/docs/data-models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/waitlist'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/dashboard/getting-started'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/data-freshness'
    | '/docs/errors'
    | '/docs/getting-started'
    | '/docs/openapi'
    | '/docs/rate-limits'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/legal/privacy'
    | '/legal/terms'
    | '/docs/$category/$operationId'
    | '/docs/data-models/$group'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
    | '/docs/$category'
    | '/docs/data-models'
  id:
    | '__root__'
    | '/_marketing'
    | '/dashboard'
    | '/docs'
    | '/sign-in'
    | '/sign-up'
    | '/waitlist'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/pricing'
    | '/dashboard/getting-started'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/data-freshness'
    | '/docs/errors'
    | '/docs/getting-started'
    | '/docs/openapi'
    | '/docs/rate-limits'
    | '/_marketing/'
    | '/dashboard/'
    | '/docs/'
    | '/_marketing/legal/privacy'
    | '/_marketing/legal/terms'
    | '/docs/$category/$operationId'
    | '/docs/data-models/$group'
    | '/dashboard/billing/'
    | '/dashboard/keys/'
    | '/dashboard/settings/'
    | '/docs/$category/'
    | '/docs/data-models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/docs/rate-limits': {
      id: '/docs/rate-limits'
      path: '/rate-limits'
      fullPath: '/docs/rate-limits'
      preLoaderRoute: typeof DocsRateLimitsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/openapi': {
      id: '/docs/openapi'
      path: '/openapi'
      fullPath: '/docs/openapi'
      preLoaderRoute: typeof DocsOpenapiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/data-freshness': {
      id: '/docs/data-freshness'
      path: '/data-freshness'
      fullPath: '/docs/data-freshness'
      preLoaderRoute: typeof DocsDataFreshnessRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/authentication': {
      id: '/docs/authentication'
      path: '/authentication'
      fullPath: '/docs/authentication'
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/getting-started': {
      id: '/dashboard/getting-started'
      path: '/getting-started'
      fullPath: '/dashboard/getting-started'
      preLoaderRoute: typeof DashboardGettingStartedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/docs/data-models/': {
      id: '/docs/data-models/'
      path: '/data-models'
      fullPath: '/docs/data-models/'
      preLoaderRoute: typeof DocsDataModelsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$category/': {
      id: '/docs/$category/'
      path: '/$category'
      fullPath: '/docs/$category/'
      preLoaderRoute: typeof DocsCategoryIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys/': {
      id: '/dashboard/keys/'
      path: '/keys'
      fullPath: '/dashboard/keys/'
      preLoaderRoute: typeof DashboardKeysIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/data-models/$group': {
      id: '/docs/data-models/$group'
      path: '/data-models/$group'
      fullPath: '/docs/data-models/$group'
      preLoaderRoute: typeof DocsDataModelsGroupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$category/$operationId': {
      id: '/docs/$category/$operationId'
      path: '/$category/$operationId'
      fullPath: '/docs/$category/$operationId'
      preLoaderRoute: typeof DocsCategoryOperationIdRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_marketing/legal/terms': {
      id: '/_marketing/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof MarketingLegalTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/privacy': {
      id: '/_marketing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof MarketingLegalPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingLegalPrivacyRoute: typeof MarketingLegalPrivacyRoute
  MarketingLegalTermsRoute: typeof MarketingLegalTermsRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingLegalPrivacyRoute: MarketingLegalPrivacyRoute,
  MarketingLegalTermsRoute: MarketingLegalTermsRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DashboardRouteChildren {
  DashboardGettingStartedRoute: typeof DashboardGettingStartedRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardKeysIndexRoute: typeof DashboardKeysIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGettingStartedRoute: DashboardGettingStartedRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardKeysIndexRoute: DashboardKeysIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsDataFreshnessRoute: typeof DocsDataFreshnessRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsOpenapiRoute: typeof DocsOpenapiRoute
  DocsRateLimitsRoute: typeof DocsRateLimitsRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCategoryOperationIdRoute: typeof DocsCategoryOperationIdRoute
  DocsDataModelsGroupRoute: typeof DocsDataModelsGroupRoute
  DocsCategoryIndexRoute: typeof DocsCategoryIndexRoute
  DocsDataModelsIndexRoute: typeof DocsDataModelsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsDataFreshnessRoute: DocsDataFreshnessRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsOpenapiRoute: DocsOpenapiRoute,
  DocsRateLimitsRoute: DocsRateLimitsRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsCategoryOperationIdRoute: DocsCategoryOperationIdRoute,
  DocsDataModelsGroupRoute: DocsDataModelsGroupRoute,
  DocsCategoryIndexRoute: DocsCategoryIndexRoute,
  DocsDataModelsIndexRoute: DocsDataModelsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
