/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DocsWindsAloftRouteImport } from './routes/docs/winds-aloft'
import { Route as DocsRateLimitsRouteImport } from './routes/docs/rate-limits'
import { Route as DocsPirepsRouteImport } from './routes/docs/pireps'
import { Route as DocsOpenapiRouteImport } from './routes/docs/openapi'
import { Route as DocsObstaclesRouteImport } from './routes/docs/obstacles'
import { Route as DocsNotamsRouteImport } from './routes/docs/notams'
import { Route as DocsNavLogRouteImport } from './routes/docs/nav-log'
import { Route as DocsMetarsTafsRouteImport } from './routes/docs/metars-tafs'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsGAirmetsRouteImport } from './routes/docs/g-airmets'
import { Route as DocsErrorsRouteImport } from './routes/docs/errors'
import { Route as DocsDocumentsRouteImport } from './routes/docs/documents'
import { Route as DocsDensityAltitudeRouteImport } from './routes/docs/density-altitude'
import { Route as DocsCrosswindRouteImport } from './routes/docs/crosswind'
import { Route as DocsBearingDistanceRouteImport } from './routes/docs/bearing-distance'
import { Route as DocsAuthenticationRouteImport } from './routes/docs/authentication'
import { Route as DocsApiReferenceRouteImport } from './routes/docs/api-reference'
import { Route as DocsAirspaceRouteImport } from './routes/docs/airspace'
import { Route as DocsAirportsRouteImport } from './routes/docs/airports'
import { Route as DocsAirmetsSigmetsRouteImport } from './routes/docs/airmets-sigmets'
import { Route as DashboardGettingStartedRouteImport } from './routes/dashboard/getting-started'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardKeysIndexRouteImport } from './routes/dashboard/keys/index'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard/billing/index'
import { Route as MarketingLegalTermsRouteImport } from './routes/_marketing/legal/terms'
import { Route as MarketingLegalPrivacyRouteImport } from './routes/_marketing/legal/privacy'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DocsWindsAloftRoute = DocsWindsAloftRouteImport.update({
  id: '/winds-aloft',
  path: '/winds-aloft',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRateLimitsRoute = DocsRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPirepsRoute = DocsPirepsRouteImport.update({
  id: '/pireps',
  path: '/pireps',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOpenapiRoute = DocsOpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => DocsRoute,
} as any)
const DocsObstaclesRoute = DocsObstaclesRouteImport.update({
  id: '/obstacles',
  path: '/obstacles',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNotamsRoute = DocsNotamsRouteImport.update({
  id: '/notams',
  path: '/notams',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNavLogRoute = DocsNavLogRouteImport.update({
  id: '/nav-log',
  path: '/nav-log',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMetarsTafsRoute = DocsMetarsTafsRouteImport.update({
  id: '/metars-tafs',
  path: '/metars-tafs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGAirmetsRoute = DocsGAirmetsRouteImport.update({
  id: '/g-airmets',
  path: '/g-airmets',
  getParentRoute: () => DocsRoute,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocumentsRoute = DocsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDensityAltitudeRoute = DocsDensityAltitudeRouteImport.update({
  id: '/density-altitude',
  path: '/density-altitude',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCrosswindRoute = DocsCrosswindRouteImport.update({
  id: '/crosswind',
  path: '/crosswind',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBearingDistanceRoute = DocsBearingDistanceRouteImport.update({
  id: '/bearing-distance',
  path: '/bearing-distance',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAirspaceRoute = DocsAirspaceRouteImport.update({
  id: '/airspace',
  path: '/airspace',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAirportsRoute = DocsAirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAirmetsSigmetsRoute = DocsAirmetsSigmetsRouteImport.update({
  id: '/airmets-sigmets',
  path: '/airmets-sigmets',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardGettingStartedRoute = DashboardGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysIndexRoute = DashboardKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingLegalTermsRoute = MarketingLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalPrivacyRoute = MarketingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/pricing': typeof MarketingPricingRoute
  '/dashboard/getting-started': typeof DashboardGettingStartedRoute
  '/docs/airmets-sigmets': typeof DocsAirmetsSigmetsRoute
  '/docs/airports': typeof DocsAirportsRoute
  '/docs/airspace': typeof DocsAirspaceRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/bearing-distance': typeof DocsBearingDistanceRoute
  '/docs/crosswind': typeof DocsCrosswindRoute
  '/docs/density-altitude': typeof DocsDensityAltitudeRoute
  '/docs/documents': typeof DocsDocumentsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/g-airmets': typeof DocsGAirmetsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/metars-tafs': typeof DocsMetarsTafsRoute
  '/docs/nav-log': typeof DocsNavLogRoute
  '/docs/notams': typeof DocsNotamsRoute
  '/docs/obstacles': typeof DocsObstaclesRoute
  '/docs/openapi': typeof DocsOpenapiRoute
  '/docs/pireps': typeof DocsPirepsRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/docs/winds-aloft': typeof DocsWindsAloftRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/keys/': typeof DashboardKeysIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/pricing': typeof MarketingPricingRoute
  '/dashboard/getting-started': typeof DashboardGettingStartedRoute
  '/docs/airmets-sigmets': typeof DocsAirmetsSigmetsRoute
  '/docs/airports': typeof DocsAirportsRoute
  '/docs/airspace': typeof DocsAirspaceRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/bearing-distance': typeof DocsBearingDistanceRoute
  '/docs/crosswind': typeof DocsCrosswindRoute
  '/docs/density-altitude': typeof DocsDensityAltitudeRoute
  '/docs/documents': typeof DocsDocumentsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/g-airmets': typeof DocsGAirmetsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/metars-tafs': typeof DocsMetarsTafsRoute
  '/docs/nav-log': typeof DocsNavLogRoute
  '/docs/notams': typeof DocsNotamsRoute
  '/docs/obstacles': typeof DocsObstaclesRoute
  '/docs/openapi': typeof DocsOpenapiRoute
  '/docs/pireps': typeof DocsPirepsRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/docs/winds-aloft': typeof DocsWindsAloftRoute
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/keys': typeof DashboardKeysIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/dashboard/getting-started': typeof DashboardGettingStartedRoute
  '/docs/airmets-sigmets': typeof DocsAirmetsSigmetsRoute
  '/docs/airports': typeof DocsAirportsRoute
  '/docs/airspace': typeof DocsAirspaceRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/bearing-distance': typeof DocsBearingDistanceRoute
  '/docs/crosswind': typeof DocsCrosswindRoute
  '/docs/density-altitude': typeof DocsDensityAltitudeRoute
  '/docs/documents': typeof DocsDocumentsRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/g-airmets': typeof DocsGAirmetsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/metars-tafs': typeof DocsMetarsTafsRoute
  '/docs/nav-log': typeof DocsNavLogRoute
  '/docs/notams': typeof DocsNotamsRoute
  '/docs/obstacles': typeof DocsObstaclesRoute
  '/docs/openapi': typeof DocsOpenapiRoute
  '/docs/pireps': typeof DocsPirepsRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/docs/winds-aloft': typeof DocsWindsAloftRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_marketing/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/_marketing/legal/terms': typeof MarketingLegalTermsRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/keys/': typeof DashboardKeysIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/dashboard/getting-started'
    | '/docs/airmets-sigmets'
    | '/docs/airports'
    | '/docs/airspace'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/bearing-distance'
    | '/docs/crosswind'
    | '/docs/density-altitude'
    | '/docs/documents'
    | '/docs/errors'
    | '/docs/g-airmets'
    | '/docs/getting-started'
    | '/docs/metars-tafs'
    | '/docs/nav-log'
    | '/docs/notams'
    | '/docs/obstacles'
    | '/docs/openapi'
    | '/docs/pireps'
    | '/docs/rate-limits'
    | '/docs/winds-aloft'
    | '/dashboard/'
    | '/docs/'
    | '/legal/privacy'
    | '/legal/terms'
    | '/dashboard/billing/'
    | '/dashboard/keys/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/dashboard/getting-started'
    | '/docs/airmets-sigmets'
    | '/docs/airports'
    | '/docs/airspace'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/bearing-distance'
    | '/docs/crosswind'
    | '/docs/density-altitude'
    | '/docs/documents'
    | '/docs/errors'
    | '/docs/g-airmets'
    | '/docs/getting-started'
    | '/docs/metars-tafs'
    | '/docs/nav-log'
    | '/docs/notams'
    | '/docs/obstacles'
    | '/docs/openapi'
    | '/docs/pireps'
    | '/docs/rate-limits'
    | '/docs/winds-aloft'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/legal/privacy'
    | '/legal/terms'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_marketing'
    | '/dashboard'
    | '/docs'
    | '/sign-in'
    | '/sign-up'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/pricing'
    | '/dashboard/getting-started'
    | '/docs/airmets-sigmets'
    | '/docs/airports'
    | '/docs/airspace'
    | '/docs/api-reference'
    | '/docs/authentication'
    | '/docs/bearing-distance'
    | '/docs/crosswind'
    | '/docs/density-altitude'
    | '/docs/documents'
    | '/docs/errors'
    | '/docs/g-airmets'
    | '/docs/getting-started'
    | '/docs/metars-tafs'
    | '/docs/nav-log'
    | '/docs/notams'
    | '/docs/obstacles'
    | '/docs/openapi'
    | '/docs/pireps'
    | '/docs/rate-limits'
    | '/docs/winds-aloft'
    | '/_marketing/'
    | '/dashboard/'
    | '/docs/'
    | '/_marketing/legal/privacy'
    | '/_marketing/legal/terms'
    | '/dashboard/billing/'
    | '/dashboard/keys/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/docs/winds-aloft': {
      id: '/docs/winds-aloft'
      path: '/winds-aloft'
      fullPath: '/docs/winds-aloft'
      preLoaderRoute: typeof DocsWindsAloftRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/rate-limits': {
      id: '/docs/rate-limits'
      path: '/rate-limits'
      fullPath: '/docs/rate-limits'
      preLoaderRoute: typeof DocsRateLimitsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/pireps': {
      id: '/docs/pireps'
      path: '/pireps'
      fullPath: '/docs/pireps'
      preLoaderRoute: typeof DocsPirepsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/openapi': {
      id: '/docs/openapi'
      path: '/openapi'
      fullPath: '/docs/openapi'
      preLoaderRoute: typeof DocsOpenapiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/obstacles': {
      id: '/docs/obstacles'
      path: '/obstacles'
      fullPath: '/docs/obstacles'
      preLoaderRoute: typeof DocsObstaclesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/notams': {
      id: '/docs/notams'
      path: '/notams'
      fullPath: '/docs/notams'
      preLoaderRoute: typeof DocsNotamsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nav-log': {
      id: '/docs/nav-log'
      path: '/nav-log'
      fullPath: '/docs/nav-log'
      preLoaderRoute: typeof DocsNavLogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/metars-tafs': {
      id: '/docs/metars-tafs'
      path: '/metars-tafs'
      fullPath: '/docs/metars-tafs'
      preLoaderRoute: typeof DocsMetarsTafsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/g-airmets': {
      id: '/docs/g-airmets'
      path: '/g-airmets'
      fullPath: '/docs/g-airmets'
      preLoaderRoute: typeof DocsGAirmetsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/documents': {
      id: '/docs/documents'
      path: '/documents'
      fullPath: '/docs/documents'
      preLoaderRoute: typeof DocsDocumentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/density-altitude': {
      id: '/docs/density-altitude'
      path: '/density-altitude'
      fullPath: '/docs/density-altitude'
      preLoaderRoute: typeof DocsDensityAltitudeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/crosswind': {
      id: '/docs/crosswind'
      path: '/crosswind'
      fullPath: '/docs/crosswind'
      preLoaderRoute: typeof DocsCrosswindRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/bearing-distance': {
      id: '/docs/bearing-distance'
      path: '/bearing-distance'
      fullPath: '/docs/bearing-distance'
      preLoaderRoute: typeof DocsBearingDistanceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/authentication': {
      id: '/docs/authentication'
      path: '/authentication'
      fullPath: '/docs/authentication'
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/airspace': {
      id: '/docs/airspace'
      path: '/airspace'
      fullPath: '/docs/airspace'
      preLoaderRoute: typeof DocsAirspaceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/airports': {
      id: '/docs/airports'
      path: '/airports'
      fullPath: '/docs/airports'
      preLoaderRoute: typeof DocsAirportsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/airmets-sigmets': {
      id: '/docs/airmets-sigmets'
      path: '/airmets-sigmets'
      fullPath: '/docs/airmets-sigmets'
      preLoaderRoute: typeof DocsAirmetsSigmetsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/getting-started': {
      id: '/dashboard/getting-started'
      path: '/getting-started'
      fullPath: '/dashboard/getting-started'
      preLoaderRoute: typeof DashboardGettingStartedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys/': {
      id: '/dashboard/keys/'
      path: '/keys'
      fullPath: '/dashboard/keys/'
      preLoaderRoute: typeof DashboardKeysIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/legal/terms': {
      id: '/_marketing/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof MarketingLegalTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/privacy': {
      id: '/_marketing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof MarketingLegalPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingLegalPrivacyRoute: typeof MarketingLegalPrivacyRoute
  MarketingLegalTermsRoute: typeof MarketingLegalTermsRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingLegalPrivacyRoute: MarketingLegalPrivacyRoute,
  MarketingLegalTermsRoute: MarketingLegalTermsRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DashboardRouteChildren {
  DashboardGettingStartedRoute: typeof DashboardGettingStartedRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardKeysIndexRoute: typeof DashboardKeysIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGettingStartedRoute: DashboardGettingStartedRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardKeysIndexRoute: DashboardKeysIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsAirmetsSigmetsRoute: typeof DocsAirmetsSigmetsRoute
  DocsAirportsRoute: typeof DocsAirportsRoute
  DocsAirspaceRoute: typeof DocsAirspaceRoute
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsBearingDistanceRoute: typeof DocsBearingDistanceRoute
  DocsCrosswindRoute: typeof DocsCrosswindRoute
  DocsDensityAltitudeRoute: typeof DocsDensityAltitudeRoute
  DocsDocumentsRoute: typeof DocsDocumentsRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsGAirmetsRoute: typeof DocsGAirmetsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsMetarsTafsRoute: typeof DocsMetarsTafsRoute
  DocsNavLogRoute: typeof DocsNavLogRoute
  DocsNotamsRoute: typeof DocsNotamsRoute
  DocsObstaclesRoute: typeof DocsObstaclesRoute
  DocsOpenapiRoute: typeof DocsOpenapiRoute
  DocsPirepsRoute: typeof DocsPirepsRoute
  DocsRateLimitsRoute: typeof DocsRateLimitsRoute
  DocsWindsAloftRoute: typeof DocsWindsAloftRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAirmetsSigmetsRoute: DocsAirmetsSigmetsRoute,
  DocsAirportsRoute: DocsAirportsRoute,
  DocsAirspaceRoute: DocsAirspaceRoute,
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsBearingDistanceRoute: DocsBearingDistanceRoute,
  DocsCrosswindRoute: DocsCrosswindRoute,
  DocsDensityAltitudeRoute: DocsDensityAltitudeRoute,
  DocsDocumentsRoute: DocsDocumentsRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsGAirmetsRoute: DocsGAirmetsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsMetarsTafsRoute: DocsMetarsTafsRoute,
  DocsNavLogRoute: DocsNavLogRoute,
  DocsNotamsRoute: DocsNotamsRoute,
  DocsObstaclesRoute: DocsObstaclesRoute,
  DocsOpenapiRoute: DocsOpenapiRoute,
  DocsPirepsRoute: DocsPirepsRoute,
  DocsRateLimitsRoute: DocsRateLimitsRoute,
  DocsWindsAloftRoute: DocsWindsAloftRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
